package simx.core.ontology.entities

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

import simx.core.entity.Entity
import simx.core.svaractor.SVarActor

class Arm( e : Entity, a : SVarActor ) extends Entity(e)(a) 

class Bucket( e : Entity, a : SVarActor ) extends Entity(e)(a) 

class CircularProgressBar( e : Entity, a : SVarActor ) extends Entity(e)(a) 

class Ghost( e : Entity, a : SVarActor ) extends Entity(e)(a) 
class GuiEffect( e : Entity, a : SVarActor ) extends Entity(e)(a) 
class GuiElement( e : Entity, a : SVarActor ) extends Entity(e)(a) 

class ManaPotion( e : Entity, a : SVarActor ) extends Entity(e)(a) 

class User( e : Entity, a : SVarActor ) extends Entity(e)(a) 