package simx.core.ontology.entities

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

import simx.core.ontology
import simx.core.entity.description.EntityAspect
import simx.core.ontology.SpecificDescription

case class ArmEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Arm, asps.toList, simx.core.ontology.types.Acceleration, simx.core.ontology.types.Mass, simx.core.ontology.types.Transformation, simx.core.ontology.types.Alignment, simx.core.ontology.types.Velocity)

case class BarrelEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Barrel, asps.toList)
case class BucketEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Bucket, asps.toList)

case class GhostEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Ghost, asps.toList, simx.core.ontology.types.Acceleration, simx.core.ontology.types.Mass, simx.core.ontology.types.Transformation, simx.core.ontology.types.Velocity)
case class GuiElementEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.GuiElement, asps.toList)

case class HandEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Hand, asps.toList, simx.core.ontology.types.Acceleration, simx.core.ontology.types.Mass, simx.core.ontology.types.Transformation, simx.core.ontology.types.Alignment, simx.core.ontology.types.Velocity)
case class HeadEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Head, asps.toList, simx.core.ontology.types.Acceleration, simx.core.ontology.types.Mass, simx.core.ontology.types.Transformation, simx.core.ontology.types.Velocity)

case class ManaPotionEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.ManaPotion, asps.toList)

case class SoundEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Sound, asps.toList)

case class UserEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.User, asps.toList, simx.core.ontology.types.Acceleration, simx.core.ontology.types.Mass, simx.core.ontology.types.Transformation, simx.core.ontology.types.Velocity)

case class WellEntityDescription( asps : EntityAspect* ) extends SpecificDescription(ontology.types.Well, asps.toList, simx.core.ontology.types.Acceleration, simx.core.ontology.types.Mass, simx.core.ontology.types.Transformation, simx.core.ontology.types.Velocity)